config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  #get syntax: '<route>' => '<controller>#<method>'
  root 'articles#index'

  get '/articles', to: 'articles#index', as: 'articles_index'

  get '/articles/new', to: 'articles#new', as: 'articles_new'

  get '/articles/:id/edit', to: 'articles#edit', as: 'articles_edit', id: /\d+/
  put '/articles/:id', to: 'articles#update', as: 'articles_update'

  delete '/articles/:id/delete', to: 'articles#destroy', as: 'articles_delete'
  # delete '/articles/:id', to: 'articles#destroy' as: 'articles_delete'

  get '/articles/:id', to: 'articles#show', as: 'articles_show', id: /\d+/

  post '/articles' => 'articles#create', as: 'article_create'
  

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

    validates :name, presence: true, uniqueness: true
    validates :body, presence: true, length: {minimum: 10}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def index                       #name convention for method that displays all
        @articles = Article.all.order("updated_at DESC")
    end

    def new                         #name convention for method that creates new
        @article = Article.new
    end

    def show
        @article = Article.find(params[:id])
    end

    def create
        @article = Article.new(article_params)

        if @article.valid?
            @article.save
            redirect_to '/' 
            
        else
            render :new
        end
    end

    def edit
        @article = Article.find(params[:id])
    end

    def update
        @article = Article.find(params[:id])
        if @article.update(article_params)
            redirect_to '/'
        else
            render :edit
        end
    end

    def destroy
        @article = Article.find(params[:id])
        @article.destroy
        redirect_to '/'
    end


    private
    def article_params
        params.require(:article).permit(:name, :body)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_footer.html.erb
<!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
    
    <script>
            $(function () {
                $(".increment").click(function () {
                    var count = parseInt($("~ .count", this).text());

                    if ($(this).hasClass("up")) {
                        var count = count + 1;
                        $("~ .count", this).text(count);
                    }
                    
                    else {
                        var count = count - 1;
                        $("~ .count", this).text(count);
                    }

                    $(this).parent().addClass("bump");

                    setTimeout(function () {
                        $(this).parent().removeClass("bump");
                    }, 400);
                });
            });

            //limit voting to only 1 per user
            //use local storage maybe? cookies?

    </script>
    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
    -->

app/views/articles/_form.html.erb
<%= form_with scope: :article, url: article_create_path, local: true do |f| %>
        <%# url attr is where the user is redirected once the form is submitted
        url: use alias for value; you can view aliases by issuing the command:
        rails routes outside rails console %>

    <div>
        <% if @article.errors.any? %>
        <ul>
            <% @article.errors.full_messages.each do |msg| %>
                <li class="alert alert-danger" role="alert" ><%= msg %></li>
            <% end %>
        </ul>
        <% end %>
    </div>


    <div>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>

    <div>
        <%= f.label :body %>
        <%= f.text_area :body, size: '100x20' %>
    </div>

    <div>
        <%= f.submit :Post, class: 'btn btn-primary'%>
    </div>

<% end %>

app/views/articles/_head.html.erb
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <title>Test Blog</title>
</head>

app/views/articles/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/">Blogs</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/articles/new">Write a blog</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-primary" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/articles/_votes.html.erb
<div class="vote circle">
  <div class="increment up"></div>
  <div class="increment down"></div>
  
  <div class="count">0</div>
</div>

app/views/articles/edit.html.erb
<!doctype html>
<html lang="en">

  <%= render 'articles/head' %>

  <body>
    <%= render 'articles/nav' %>
    <div class='container'>
        <%= form_with scope: :article, url: articles_update_path, method: :put, local: true do |f| %>
        <%# url attr is where the user is redirected once the form is submitted
        url: use alias for value; you can view aliases by issuing the command:
        rails routes outside rails console %>

    <div>
        <% if @article.errors.any? %>
        <ul>
            <% @article.errors.full_messages.each do |msg| %>
                <li class="alert alert-danger" role="alert" ><%= msg %></li>
            <% end %>
        </ul>
        <% end %>
    </div>


    <div>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>

    <div>
        <%= f.label :body %>
        <%= f.text_area :body, size: '100x7' %>
    </div>

    <div>
        <%= f.submit :Update, class: 'btn btn-primary' %>
    </div>

        <% end %>
    </div>
    
   <%= render 'articles/footer' %>
  </body>
</html>

app/views/articles/index.html.erb
<!doctype html>
<html lang="en">

  <%= render 'articles/head' %>

  <body>
    <%= render 'articles/nav' %>
    <div class='container'>
        <br/>
        <h1>Welcome to this test blogsite!</h1>
        <table class='table table-borderless'>
            <thead>
                <tr>
                    <!--<th scope="col">ID</th>-->
                    <th></th>
                    <th scope="col" class="w-25">Title</th>
                    <th scope="col" class="w-75">Body</th>
                </tr>
            </thead>

            <tbody>
                <% @articles.each do |article| %>
                    <tr>
                        <!--<td><%#= article.id %></td>-->
                        <td class="align-middle"><%= render 'articles/votes' %></td>
                        <td class="align-middle"><%= article.name %></td>
                        <td class="align-middle"><%= article.body[0..160] %></td>
                        <td class="align-middle"><%= link_to 'View', articles_show_path(article), method: :get %></td>
                        <td class="align-middle"><%= link_to 'Edit', articles_edit_path(article), method: :get %></td>
                        <td class="align-middle"><%= link_to 'Delete', articles_delete_path(article), method: :delete, data: { confirm: "Are you sure?" } %></td>
                    </tr>
                <% end %>
            </tbody>
        </table>

        <%= link_to 'New Blog', articles_new_path, class: 'btn btn-primary'%>
        <%# <a href='/articles/new' class='btn btn-primary'>New Article</a> %>
    </div>

    <%= render 'articles/footer' %>
    
  </body>
</html>

app/views/articles/new.html.erb
<!doctype html>
<html lang="en">

  <%= render 'articles/head' %>

  <body>
    <%= render 'articles/nav' %>
    <div class='container'>
        <%= render 'form', article: @article %>
    </div>

    <%= render 'articles/footer' %>
    
  </body>
</html>

app/views/articles/show.html.erb
<!doctype html>
<html lang="en">

  <%= render 'articles/head' %>

  <body>
    

    <%= render 'articles/nav' %>
    <div class='container'>
        <br/>
        <h1><%= @article.name %></h1>
        <p><%= @article.body %></p>

        <%= link_to 'Home', '/', class: 'btn btn-primary'%>
        <%= link_to 'Edit', articles_edit_path(@article), class: 'btn btn-primary'%>
        <%= link_to 'Delete', articles_delete_path(@article), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger' %>
    </div>

    <%= render 'articles/footer' %>
    
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>